### ISSUE TITLE
unrecognized command line option ‘-mno-ms-bitfields’

### ISSUE THREAD

**Issue by karlh626** [apamment/galactic-dynasty#1]
I pulled the lastest commit using git and when attempting to compile using build.sh on Rasbian it gives the error "unrecognized command line option ‘-mno-ms-bitfields’"

An earlier version of this repo did compile successfully on the rpi but the build.sh file did not include ‘-mno-ms-bitfields’ in the syntax.

If I comment out the ‘-mno-ms-bitfields’ portion it seems to run without errors and produces the GalacticDynasty binary.

**Comment by apamment** [comment]
Thanks, the -mno-ms-bitfields was for windows, so removing it is the right thing to do
