### ISSUE TITLE
rasbian build fails on lua error

### ISSUE THREAD

**Issue by karlh626** [apamment/galactic-dynasty#2]
I just cloned the latest:

> commit 9edfe15ce1a0caf27760f9e5bf87506b9da2c1f3
> Author: Andrew Pamment <apamment@yandex.com>
> Date:   Sat Apr 22 21:51:39 2017 +1000
> Updated Mystic TXT

and I am getting the following error when I try to build:

```
ranlib libs-Linux/libODoors.a
main.c:13:17: fatal error: lua.h: No such file or directory
 #include <lua.h>
            
compilation terminated.
gcc: error: main.o: No such file or directory
```

**Comment by apamment** [comment]
Raspbian uses an old Lua, first install liblua5.2-dev then change the build.sh where it says -I/usr/include/lua5.3 to -I/usr/include/lua5.2 and on the linking like -llua5.3 to -llua5.2

**Comment by karlh626** [comment]
Ok, that worked! - thank you
